# Generated by Django 4.0.2 on 2022-02-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_alter_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='date_added',
        ),
    ]
